import Footer from "@/app/components/Footer";
import NavbarComponent from "@/app/components/HeaderComponent";
import '@/app/globals.css';
import '@/app/styles/welcomecard.webflow.css';
import '@/app/styles/webflow.css';


export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavbarComponent />
        {children}
        <Footer />
      </body>
    </html>
  );
}
